GoogleCloudPlatform/emblem

website/views/donations.py
=> feat(issue-364): adding in cloud trace for donation submission

experimental/client-app/server/proxy.js, experimental/client-app/src/components/campaign/campaign-card.js, experimental/client-app/src/components/campaign/styles/campaignCard.js, experimental/client-app/src/containers/campaign/campaign-page.js, experimental/client-app/src/containers/campaign/styles/campaignPage.js
**Issue:** Small visual updates and bug on campaign page.
To re-create bug:
1. Locate the `experimental/client-app` folder
2. Run the app in the experimental folder: `npm i & npm run dev`
3. Verify that clicking on `learn more` button on a campaign card redirects you to an empty page. 
To verify issue no longer exists:
Complete the same steps above and verify that the campaign page has been populated.
=> fix(lit): resolve campaign page not updating

website/e2e-test/smoke-test.spec.js
This should **unblock further website testing work** once merged.
Fixes b/229636866
=> feat(website/e2e-test): clean up smoke tests

.github/labeler.yml, .github/workflows/auto-label.yml
Part of #360.
This modifies the new auto-labeler workflow to apply label changes based on affected repository files.
=> feat(productivity): add PR labels for changed files

website/e2e-test/smoke-test.spec.js
=> feat(website/e2e-test): add smoke tests

website/templates/errors/403.html
=> fix(website): fix misplaced Jinja tag

website/middleware/session.py
Adds a further TODO note about GCS performance.
=> docs: add TODO note on Cloud Storage performance eval

docs/website.md, website/README.md
=> refactor(docs): move website docs into docs/

docs/decisions/2022-04-website-testing-philosophy.md, docs/tutorials/website-e2e-test.md
**DO NOT MERGE** until we migrate the website content to the `docs/` directory (#400)
Based on pairing with @raffomartini
=> feat(website/e2e-test): add README

docs/website.md
=> fix: added redirect_uri to required env vars

terraform/cleanup.sh
~**DO NOT MERGE** until #395 is merged.~
This PR adds GCP project "tear-down" functionality to `terraform/cleanup.sh`.
**Googlers:** This is part of b/229636944
=> feat(terraform): add GCP project teardown ability

terraform/cleanup.sh
=> fix(ops): remove stray comma

terraform/cleanup.sh
- Extracted from #387
- Part of #347
=> feat(ops): clean up Cloud Run-related topics

docs/decisions/2022-06-cd-pipeline-project-reuse.md
Fixes b/233664758; Part of #347
=> feat(docs): decide to recycle projects for CD pipeline

CONTRIBUTING.md, MAINTAINERS.md, README.md, docs/decisions/2021-04-cloud-build.md, docs/testing.md, docs/tutorials/setup-quickstart.md, docs/tutorials/setup-walkthrough.md
This PR started with modifying the CONTRIBUTING.md, and ended up chasing a few related random threads. A couple out of scope markdown formatting changes also got attached.
There is some light content changes and additions in this PR. In the interest of iterative improvement, I'd like to bias towards adding this and improving later.
The main review goals are:
* Regressions in clarity
* Sharing wrong information
=> docs: optimize CONTRIBUTING and related resources for new folks

docs/testing.md
Please **merge for me** once approved.
Thanks!
=> chore(docs): fix broken link

setup.sh
=> feat: add content seeding to setup.sh

setup.sh
Extracted from #482; part of #347
=> feat(delivery): add option to skip seeding prompt

installation-testing/reusable-project-setup.sh
Extracted from #482; part of #397; related to #347
=> feat(delivery): add reusable project setup script

installation-testing/builds/delivery-e2e.cloudbuild.yaml
Extracted from #482
_(Sorry about the branch name, I clicked before I renamed it! ☹️ )_
=> fix: skip session bucket creation

installation-testing/builds/delivery-e2e.cloudbuild.yaml, setup.sh
=> fix: fix SKIP_SEEDING not having a default

installation-testing/builds/e2e-deployer.cloudbuild.yaml
=> feat: add deployer image Cloud Build config

installation-testing/terraform/cleanup.sh, ops/e2e-runner-build.cloudbuild.yaml, ops/web-e2e.cloudbuild.yaml, terraform/modules/ops/build.tf, terraform/modules/ops/main.tf
Obviates #418; part of b/233774500
✅  This **has** been tested on CI.
=> feat(ops): consolidate testing Artifact Registry repos

docs/decisions/2021-08-13-session-cookies.md
#521 missed the session cookie decision content. Here it is.
=> docs: add session cookie decision content

docs/delivery.md
https://github.com/GoogleCloudPlatform/emblem/blob/main/docs/docs/images/testing-delivery-pipeline.png returned 404.
=> docs: fix img url

docs/decisions/2022-06-terraform-folder-structure.md
This decision log entry discusses the factors considered when /terraform was reorganized into a conventional Terraform structure.
=> docs: conventional Terraform decision log

experimental/client-app/src/middleware/logger.js
=> feat: adding logger to client lit app

scripts/configure_auth.sh, setup.sh
Add a wrap-up message that auth is configured to configure_auth
Add a wrap up message where to find the website to setup.sh
=> feat: add end-of-script wrap-up message to auth and setup

setup.sh
=> fix:clarify repo owner prompt in setup

website/views/campaigns.py
=> Fix: don't dump data to logs

docs/client-libraries.md
=> doc: generate client library

docs/decisions/2022-09-generated-client-library.md
=> decision: use generated library

README.md
=> fix(issue-600): Define project boundaries for Cloud products

docs/delivery.md, scripts/configure_delivery.sh
=> fix(issue-655): adding more docs around build triggers in CI/CD flow

docs/decisions/2022-11-tracing-with-otel.md
Fixes #122
Proposes use of OpenTelemetry SDK is Emblem components.
Comments welcome!
=> Proposed DR for Tracing instrumentation

CONTRIBUTING.md
This PR makes various updates to CONTRIBUTING.md
- removes outdated info
- adds some additional info
- reorganizes existing sections
- adds a table of contents
=> docs: updates to CONTRIBUTING.md

ops/terraform.cloudbuild.yaml
This PR will add `terraform.cloudbuild.yaml` to the `ops/` directory. 
This PR is part of an attempt to breakup PR #724 into smaller merges. 
Merging this PR will not impact current functionality.
=> feat: add a terraform cloudbuild config

ops/web-e2e.cloudbuild.yaml, website/requirements.txt
Fixes #756 
✅ I confirmed that tests pass [here](https://github.com/ace-n/emblem/pull/3).
=> feat(ops): split up E2E testing Cloud Build config

scripts/configure_delivery.sh, setup.sh
=> fix(testing): move E2E image build to configure-delivery script

docs/testing.md
=> fix(docs): update testing documentation

client-app/README.md, client-app/web-dev-server.config.mjs
**Issue:** Minor update to client app (lit / open-wc framework), ensure hard refresh is stable for routing
=> refactor: client app readme, routing

ops/unit-tests.cloudbuild.yaml, terraform/modules/ops/testing.tf, terraform/modules/website-e2e-test/testing.tf
Progress on #848 on revealing the test failure.
=> testing: fix silent failure of API unit tests

ops/canary.cloudbuild.yaml, ops/deploy.cloudbuild.yaml, ops/terraform.cloudbuild.yaml, ops/unit-tests.cloudbuild.yaml, ops/web-build.cloudbuild.yaml
=> mordenize cloud build yaml files with script 

content-api/requirements.txt
Resolves api-unit failures for #985.
=> fix(issue-985): resolve dependency conflicts in opentel libs

terraform/modules/ops/main.tf
=> fix: updated the script for setup.sh 

ops/e2e-runner/Dockerfile, ops/web-e2e.cloudbuild.yaml
Issue: #1017 
Related community issue https://github.com/GoogleContainerTools/kaniko/issues/1733
=> chore:  debugging kaniko image build failure

.github/labeler.yml, .github/workflows/auto-label.yml
Updating to actions/labeler would require a syntax change, so make that happen now.
=> Update labeler to v5, update syntax
