.github/workflows/auto-label.yml

This is part of #360. It lifts conventional commit prefixes from PR titles to labels, where the GitHub release notes can pick up things like breaking changes per the configuration in #382. These labels also help ensure the write labels are on the PRs, avoiding metadata gaps or manual work where the prefixes are used correctly.

testing: convert conventional commit PR titles to labels

---

setup.sh

Setting the stage for future work on automated **Delivery** testing.
This adds two environment variables to `setup.sh`:
- `SKIP_AUTH`
- `SKIP_TRIGGERS`
Setting these environment variables will enable _programmatic deployments_ of Emblem using `setup.sh`.

feat(setup.sh): add skips for non-automated processes

---

.github/workflows/auto-label.yml

The conventional release GitHub Action has configuration for type mappings between conventional commit context and GitHub labels. The action expects serialized JSON, not a YAML map. This PR is meant to correct that.

fix: conventional release mapping expects JSON

---

terraform/app/application/main.tf

This is required to comply with [UBLA-only](https://cloud.google.com/storage/docs/uniform-bucket-level-access) GCS policies.

chore(ops): use UBLA buckets

---

content-api/requirements.txt

This [_should_](https://stackoverflow.com/questions/71661851/typeerror-init-got-an-unexpected-keyword-argument-as-tuple) fix #393.

fix(content-api): update Flask version

---

.github/labeler.yml

Working my way through syntax errors. This was a parsing error in labeler.yml: `Error: YAMLException: unidentified alias ".md" (55:7)`. To address this, I'm wrapping all strings in quote marks.

fix: auto-labeler YAML syntax error

---

docs/website.md

Related issue: https://github.com/GoogleCloudPlatform/emblem/issues/370
Adds website deployment instructions explicitly in website readme.

refactor(docs): update docs to include website container deployment

---

scripts/configure_auth.sh

Related issue: https://github.com/GoogleCloudPlatform/emblem/issues/370
To clarify and not assume user executed `setup.sh` script yet. Adding in minor update to secret creation directions.

refactor(docs): minor clarification to secret directions

---

ops/e2e-deployer/Dockerfile

This will be necessary to test the `Delivery` component.
Part of #347

feat(ops): add testing image

---

setup.sh

Replaces #428; part of #347
_This is necessary so that Terraform doesn't insist on replacing buckets that already exist._

feat(delivery): import session data bucket

---

terraform/cleanup.sh

Part of #347; defragged from #387

fix(delivery): write project IDs to TF vars

---

experimental-setup.sh
terraform/environments/ops/main.tf
terraform/environments/ops/variables.tf
terraform/environments/prod/main.tf
terraform/environments/prod/variables.tf
terraform/environments/staging/main.tf
terraform/environments/staging/variables.tf
terraform/modules/emblem-app/iam.tf
terraform/modules/emblem-app/main.tf
terraform/modules/emblem-app/services.tf
terraform/modules/emblem-app/variables.tf
terraform/modules/ops/environment-build-triggers/main.tf
terraform/modules/ops/environment-build-triggers/variables.tf
terraform/modules/ops/main.tf
terraform/modules/ops/services.tf
terraform/modules/ops/triggers.tf
terraform/modules/ops/variables.tf

- experimental-setup.sh will deploy resources to the ops, staging, and prod projects and optionally run the configure_auth script. 
- Deploying triggers is disabled until we integrate them properly into the emblem-app module.

feat(terraform): integrate modular terraform

---

terraform/cleanup.sh

Part of #397; will be rebased into #482

feat(delivery): integrate TF refactor into cleanup script

---

docs/README.md

Adjust docs/README.md so the main content we want Emblem users to prefer is presented first, ahead of "manual/contributor" instructions.

docs: create the happy user path

---

setup.sh

`pr` is not supported in Alpine linux, but `cat` is
(Extracted from #487)

fix: use cat instead of pr

---

docs/README.md
docs/decisions/2021-07-cloud-identity.md
docs/decisions/2021-07-gcb-pubsub-triggers.md
docs/decisions/2021-07-user-app-auth.md
docs/decisions/2021-08-13-session-cookies.md
docs/decisions/2021-08-17-openapi-tools.md
docs/decisions/2021-11-refreshing-id-tokens.md
docs/decisions/2021-11-user-authentication.md
docs/decisions/README.md

This PR makes the following changes:
* Migrate remaining decision records from the "original format" in docs/decisions/README.md to standalone files.
* Move the decision story arcs to docs/decisions/README.md
* Add missing decisions to the deployment arc
* Add a new user authentication arc

docs: complete decision record migration and add story arcs

---

terraform/modules/emblem-app/services.tf
terraform/modules/ops/services.tf

These _seem_ to be missing, since I had to enable it when using a new (non-GCP-org) project.

fix: add missing APIs

---

.github/workflows/auto-label.yml

There's no such event as `synchronized`, so I updated the Github Action yml according the [official docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target=)
```diff
- synchronized
+ synchronize
```

fix: PR trigger in autolabeler

---

terraform/modules/ops/main.tf

Current cron configuration runs every 2 minutes. Switch to running nightly at 2am.
https://crontab.guru/ is a helpful tool to troubleshooting scheduler config.

fix: nightly cron running every 2 minutes

---

terraform/environments/prod/variables.tf

While we don't plan to do e2e testing into the prod environment, this creates a consistent environment configuration between stage & prod, and fixes an error introduced by copying main.tf code between environments.

fix: add deploy_session_bucket var to prod

---

docs/tutorials/setup-quickstart.md
docs/tutorials/setup-walkthrough.md

Updating `gcloud alpha billing` commands to `gcloud beta billing`. Minor whitespace/formatting fixes in setup-quickstart.md

fix: use beta for gcloud billing

---

ops/deploy.cloudbuild.yaml

`--set-env-vars` in the Cloud Build configuration is removing environment variables we configured via setup.sh and scripts/configure_auth.sh.
By switching to `--update-env-vars`, previously set configuration will be retained.

fix: stop deploy updates removing service configuration

---

scripts/configure_delivery.sh
setup.sh

The following change refactors setup.sh. As a result, I expect currently observed CD pipeline bugs to be resolved.
* Move trigger setup to a new scripts/configure_delivery.sh
* Move trigger setup late in the process, to ensure broken deployments aren't kicked off by the setup.sh container build
* Switch from using environment variables to manage terraform back to tfvars, so once setup is completed, any use of `terraform apply` in the local filesystem will have consistent behavior with the choices made in setup.
* If REPO_NAME and REPO_OWNER are set, skip prompt for repo

refactor: move delivery setup late and separate, use tfvars

---

terraform/modules/emblem-app/deploy.tf

The canary Cloud Builds have Pub/Sub triggers. These triggers filter on the build substitution `_SERVICE` matching the service associated with the trigger. However, at some point I simplified the trigger definition to hard-code the `_SERVICE` substitution to the known service name, instead of the Pub/Sub message.
As a result, the canary build triggers were always matching the filter whenever any Pub/Sub message reached them.
This change reverts that mistake, ensuring that a canary trigger only kicks off if the canary topic for that environment is messaging for the particular service.

fix: canary build triggers filter on matching service

---

ops/canary.cloudbuild.yaml
ops/deploy.cloudbuild.yaml

The current canary strategy is "increment by 5%". A more ideal strategy would follow a more geometric or exponential curve, but to simplify the behavior for now, increasing the interval to 20 so we have 5 canary builds instead of 20 per rollout.

fix: canary deploys by intervals of 20% instead of 5%

---

setup.sh
terraform/environments/ops/backend.tf
terraform/environments/prod/backend.tf
terraform/environments/staging/backend.tf

fixes #97 
This PR:
- Adds terraform `backend` block to each directory in `terraform/environments/`
- Adds `gsutil mb` command to setup - will create gcs bucket in ops project named `${OPS_PROJECT}-tf-states`
- Updates `terraform init` commands to use the remote backend via `-backend-config` flags
GCS bucket file structure:
- gs://${OPS_PROJECT}-tf-states
- /ops
- default.tfstate
- /stage
- default.tfstate
- /prod
- default.tfstate

feat:use remote terraform state in setup

---

ops/canary.cloudbuild.yaml
ops/deploy.cloudbuild.yaml
terraform/modules/emblem-app/deploy.tf

This was mostly removed over the course of various refactoring, but recent troubleshooting needs show it's value.
* Use the entire Pub/Sub body as a substitution
* Echo this object to the build log as the first step (before anything else can go wrong)
* Re-order substitutions in terraform config to alphabetical order to match display order in console.

fix: restore _BODY substitution to Pub/Sub triggered builds

---

website/templates/donations/new-donation.html

This can't be trusted by the API, but it might be helpful for end-users.

fix: only allow numbers in donation amount

---

website/templates/auth/logout.html
website/templates/home.html
website/views/campaigns.py

Resolves issue: #608 
**Fix:** Instead of disabling button, I've decided to hide it. If this is never to be enabled for someone 
just perusing incognito, it should only be displayed for logged in users.
**Steps to recreate:**
1) Check branch out and rebuild `website/` image and redeploy on your personal GCP
2) Without logging in, you should no longer see the button displayed on the homepage
3) Go through login and when you've landed back on the homepage you should see the button displayed again
Note: Happy to let you leverage my GCP project if necessary to review this. I will just need to add you as an approver.

fix(issue-608): hide create campaign link

---

website/static/site.css
website/templates/donations/view-donation.html

Issue: #607 
**Steps to re-create:**
Requirements, you should have a deployed `content-api` container and a fully seeded firestore. You may leverage my project if you'd like, just ping.
1) In personal GCP, redeploy `content-api` container 
2) Set env variable `EMBLEM_API_URL` to that `content-api` container url
```
export EMBLEM_API_URL=https://content-api-c55u7v66jq-uc.a.run.app/
```
3) Open `website/` and start running the flask app
```
cd website/
pip3 install -r requirements.txt
flask run
```
4) Open browser @ `http://localhost:5000/viewDonation?donation_id=00f12b60ba35489f902f`
You should see the following. Clicking `Back to Campaign` will redirect to parent campaign page.

fix(issue-607): add link back to original campaign

---

ops/e2e-runner/Dockerfile

Along with #622, this should fix the failing `web-system-tests` CI check.
Backstory:
> Playwright's Docker image was updated, but the corresponding NPM dependency was not.
>
> Even if the NPM dependency **had** been updated, it doesn't seem in-sync with the `latest`-tagged Docker image.

fix: pin Playwright Dockerfile version

---

terraform/modules/emblem-app/files/templates/campaigns.tftpl
terraform/modules/emblem-app/files/templates/causes.tftpl
terraform/modules/emblem-app/files/templates/donations.tftpl
terraform/modules/emblem-app/files/test-data/campaigns.json
terraform/modules/emblem-app/files/test-data/causes.json
terraform/modules/emblem-app/files/test-data/donations.json
terraform/modules/emblem-app/firestore.tf

Related to #644 
This adds the following to the emblem-app terraform module:
- a Firestore document resource for each object in a `causes.json` file
- a Firestore document resource for each object in a `donations.json` file
The above uses Terraform templates and json files made up from data in [sample_data.json](https://github.com/GoogleCloudPlatform/emblem/blob/main/content-api/data/sample_data.json)
Note: merging this PR will not change any Terraform functionality. The `seed_test_data` variable used is set to `false` by default so that none of the resources associated with test data is added. The resources in this module will remain dormant until `seed_test_data` is set to `true`
This will only partially address #602 
Forthcoming PR will integrate these features with `setup.sh`

refactor: Terraform to seed causes and donations test data to Firestore

---

ops/api-build.cloudbuild.yaml

**Issue:** This resolved dockerfile not found errors when api-push-to-main trigger
**To recreate the bug:**
- **Required:** You should have a full working setup of Emblem already in CloudShell or locally
- Head to the `content-api/` folder
- Update anything within this folder (`api-push-to-main` executes on any file updates in `content-api/`)
- Head over to the history tab in `https://console.cloud.google.com/cloud-build/builds` and monitor the trigger
- You should see a build failure rather quickly and a similar log as above

fix: update context in api-build.cloudbuild.yaml

---

docs/testing.md
terraform/modules/ops/build.tf

**Issues:**
*  Removing outdated reference to `website/e2e-test/Dockerfile` (since moved to `ops/e2e-runner/`)
* Both `e2e-runner-push-to-main` and `web-push-to-main` (and thus the full web delivery) gets executed if an edit is made to `website/e2e-test/`
* Fixes broken links describing e2e push to main and e2e nightly testing
**Fixes:**
* Ensures that any edits to `e2e-tests/` within `website/` only executes `e2e-runner-push-to-main` 
* Links should reference correct Tf samples referencing e2e testing

fix: decoupling triggers when an edit is made within e2e-test/

---

ops/api-build.cloudbuild.yaml
setup.sh
terraform/modules/ops/build.tf

**Issue:** Setting correct context for wherever `api-build.cloudbuild.yaml` is called.
Also fixes misspelled property `ignored_files` for web build trigger in terraform.
**To recreate bug:**
- **Required:** You will need to run the setup script in a clean project.
- Execute `sh setup.sh`
- Allow the setup script to flit through and you will eventually see the error below. Re-test to ensure that this fix can be run on initial setup AND when changes are introduced in `content-api/`

fix: adds in _CONTEXT substitution for api-build.cloudbuild.yaml

---

terraform/modules/ops/main.tf
terraform/modules/ops/services.tf
terraform/modules/ops/testing.tf
terraform/modules/ops/variables.tf

**Issue:** 
Resolves token retrieval error in `unit-tests.cloudbuild.yaml`. The curl fetch for new generated id token was throwing 
```
{'error': {'code': 403, 'message': 'The caller does not have permission', 'status': 'PERMISSION_DENIED'}}
```
permissions error due to the `cloudbuild` service account not given the correct roles.
**To recreate bug:**
-  **Required:** You should have a working full setup of Emblem already
- Create a new branch. Make any small change and create a pull request to trigger `api-unit-tests`. 
- You should a series of errors related to firestore database and permissions errors.
**Fixes:**
- Adding `roles/datastore.user` (firestore), `roles/iam.serviceAccountTokenCreator` roles to cloudbuild service account

fix: resolves api_unit_test token creation + datastore permissions issues

---

ops/api-build.cloudbuild.yaml
ops/web-build.cloudbuild.yaml
setup.sh

This PR:
- Replaces `$_SHORT_SHA` variable in api and website cloud build yaml files with `$_IMAGE_TAG`
- Adds  built-in`$SHORT_SHA` as default value in api and website cloud build yaml files
- Replaces `$SHORT_SHA` variable in `setup.sh` with `$SETUP_IMAGE_TAG`
To test:
- Run `setup.sh` from this branch (or just the build and run commands on lines 139 - 192)
- Trigger `api-deploy-to-main` and `web-deploy-to-main` build triggers using repo with this branch's changes.
Result:
- Builds from `setup.sh` will be tagged as `setup` in artifact registry.
- Builds from triggers will be tagged with short commit sha in artifact registry
Fixes #667

fix: _SHORT_SHA variable usage

---

renovate.json

* Drop experimental from renovate, it will be up to the experimenter to track updates and make sure current dependencies are in place for final implementation code.
* Switch the schedule to a 3 week cycle on Mondays. This is designed to: Not trigger weekend notifications, be slightly off-cycle our team's 2-week rotation on maintenance work to ensure it doesn't synchronize with specific engineers.
I checked the validity of this schedule with https://codepen.io/rationaltiger24/full/ZExQEgK

chore: update renovate schedule (3 weeks)

---

content-api/data/cloudbuild.yaml
content-api/data/requirements.txt
setup.sh
terraform/modules/emblem-app/main.tf

This PR will:
- add a `requirements.txt` and `cloudbuild.yaml` to the `content-api/data` directory to support executing seed scripts in a cloud build job
- add the IAM role `datastore user` to the ops cloud build service account in the application Terraform module to allow the build job to seed firestore
- change the seeding step in `setup.sh` to use `gcloud builds submit` instead of python
Fixes #657 
Fixes #602

fix: seed Firestore via build job

---

terraform/clean_project_setup.sh

move over to beta since managing billing in projects is in beta now. (assuming beta might be more stable than alpha) 
https://cloud.google.com/sdk/gcloud/reference/beta/billing/projects/link

nit: billings projects link is in beta now

---

terraform/modules/emblem-app/deploy.tf
terraform/modules/ops/build.tf
terraform/modules/ops/testing.tf

**Issue:** #557  Adding more color to what each build trigger does. 
**To reproduce:**
* Execute full script `sh setup.sh` or solely delivery (if you have a working version of Emblem already set up) `scripts/configure_delivery.sh` to update terraform `google_cloudbuild_trigger` resources
* After full deployment, you should see the descriptions for each trigger updated like so:

feat(issue-557): adding descriptions for build triggers

---

setup.sh

This PR will:
- add the `--project` flag to all instances of `gcloud builds describe` used in `setup.sh` to specify ops project. 
Fixes #699

fix: add project flag to `gcloud builds describe` in `setup.sh`

---

README.md

**Issue:** Add clarifying step for when we direct users to connect Cloud Build Triggers w/ a forked emblem repo

refactor: update readme to enable build api for first step

---

scripts/configure_delivery.sh

This PR will update `configure_delivery.sh`:
- Prompt to press any key to continue will accept any key - previously only accepted Enter
- Prompt to verify repository URL will accept Enter key and variations of 'yes' ('y', 'Y', 'yes', 'YES') - previously only accepted 'y'
Fixes #701

feature: adjust prompts in `configure_delivery.sh`

---

terraform/modules/emblem-app/deploy.tf

This PR:
- updates 4 `google_cloudbuild_trigger` resources in the emblem-app module to use the `filename` parameter instead of the `git_file_source` block
fixes #718 
This causes no change to resources but will prevent Terraform anticipating changes upon re-run.

fix: terraform build trigger filename parameter

---

scripts/configure_delivery.sh
setup.sh

This fixes many of the key issues in #713 
Which it turned out had less to do with POSIX compliance as it did with us explicitly calling sub-scripts configure-delivery and configure-auth using sh. Removing this call lets the shebang at the top of the files do their work so they end up being run with the environment bash.
On some machines, sh is bash so this wasn't an issue, but on many machines sh is a POSIX compliant dash variant.
This PR changes those calls to not run with sh, and also removes a weird conditional discovered in the process.

fix: Call sub-scripts with bash instead of sh

---

scripts/bootstrap.sh
scripts/configure_delivery.sh
setup.sh
terraform/modules/ops/services.tf
terraform/modules/ops/testing.tf

This PR is dependent on the following:
-  #730 for terraform build config 
- #734 for bootstrap script
This PR makes the following changes:
- executes `bootstrap.sh` from `setup.sh`
- executes ops, prod, and stage terraform via cloud build jobs
- updates `configure_delivery.sh` to use `repo_name` and `repo_owner` from project metadata defined in `bootstrap.sh`
This PR will also remove the following from `setup.sh` and `configure_delivery.sh` 
- Terraform bucket creation
- prompt for connecting repo to ops project
1. Set Emblem environment variables (`OPS_PROJECT`, `PROD_PROJECT`, `STAGE_PROJECT`)
2. Run `setup.sh`
3. Confirm successful deployment 
4. Make change in `web` directory in  forked repo to test deployment pipeline
5. Make change to `content_api` directory in forked repo to test …

feat: run setup terraform via build jobs

---

website/e2e-test/package-lock.json

This PR updates a generated file so that E2E tests will pass.
✅  _Website E2E tests are **passing** under this PR._
> (Ignore the `emblem-ops` failure; that check is deprecated.)

fix(website/e2e-test): update package.json

---

terraform/environments/staging/main.tf

cleaning up some nails.
This block will reappear in `environments/ops/main.tf` in a forthcoming PR.

chore: remove unused e2e test module block

---

terraform/environments/ops/main.tf
terraform/modules/ops/services.tf

fix(ops): enable Cloud Run API in Terraform

---

ops/web-e2e.cloudbuild.yaml
terraform/modules/website-e2e-test/testing.tf

This PR will:
- replace the _PROJECT substitution variable with the built-in PROJECT_ID variable in the e2e testing module cloud build config

use built-in project var in e2e module

---

renovate.json

Similar to #802, instructs Renovate to group all otel libraries to update as a unit. Individually they typically fail testing.
Once merged, follow-up to see how to get renovate to revisit separate opentelemetry update PRs that will fail testing (e.g., #800)

testing: group openetelemetry dependency updates in single PR

---

docs/decisions/2023-03-31-playwright-dependencies.md
renovate.json5

Fixes #847
Many changes show up in this PR.
* Group majors along with Node.js devDependencies, which ends up grouping major update and non-major updates in two different PRs.
* Have renovate check for OpenTelemetry and Playwright updates every day before EST business hours. This is to address staggered package release.
* Fix grouping by JavaScript: Renovate pays attention to `node` and `js`, not `javascript`. 🤦 
* Formatting: Converge closer on line length 80 and make use of the space where it was oddly shortened.
* Add #847 as a follow-up reference to the decision record.
* Add a reviewer note for OpenTelemetry and Playwright PRs to provide additional guidance
```
npm install -g renovate
LOG_LEVEL=debug renovate --dry-run --token $(gh auth token) grayside/emblem > renovate.out
```
In …

deps: improve grouping and reviewer guidance

---

content-api/requirements.txt
website/requirements.txt

**Issue:** To resolve `api-unit-test` failures in recent PRs siting `ModuleNotFoundError: No module named 'google' from google.auth.transport import requests as reqs`. 
Ex: https://github.com/GoogleCloudPlatform/emblem/pull/913

fix: updating from google.auth to google-auth

---

ops/web-e2e.cloudbuild.yaml
scripts/configure_delivery.sh

**Issue:** Updating references from old `e2e-runner-build` to new `web-e2e` and substitution expectations that go with it.
* Updating old `e2e-runner-build` file ref
* Updating substitutions

fix: small fix for web-e2e build trigger

---

.gitignore
content-api/data/seed_database.py
content-api/main.py
content-api/main_approver_test.py
content-api/main_nonapprover_test.py
content-api/requirements.txt

Fix Issue: #848  
**Part 1:** Wrap python unit tests to fail when exception is thrown
**Part 2:** Prevent otel running during unit test runs
**To verify:** 
Open `api-unit-tests` check below and `Unit tests` step (last step) should no longer be displaying `Error while writing to Cloud Trace` logs related to otel.
Before fix:
After fix:

fix(issue-848): resolve silent errors in api unit tests

---

content-api/requirements.txt
ops/unit-tests.cloudbuild.yaml

Fixes: #953 
To understand issue:
* Latest related error log https://pantheon.corp.google.com/cloud-build/builds;region=global/5e1239d2-a7e5-4501-9c4e-449cfb4ad86a?project=emblem-ci-ops
Actions taken:
* Updates `google-auth`
* Restores back to `requirements.txt` rather than referencing `requirements-test.txt` twice in unit-test.cloudbuild.yaml (main fix - ref: https://github.com/GoogleCloudPlatform/emblem/commit/003d6d501c6f568c56ed77bd3eaff6b4c5ba47a4)

fix: wrong requirements txt ref in unit test cloudbuild yaml

---

content-api/requirements.txt

Resolving in `opentelemetry-semantic-conventions==0.41b0` mismatch in
PR: https://github.com/GoogleCloudPlatform/emblem/pull/995

fix: otel mismatching deps
